version: '1.0'
networks:
  bundlecore-net:

services:
  db:
    networks:
      - bundlecore-net
    # restart: always
    image: postgres:latest
    container_name: bundlecore-db
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bundleCore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10

  frontend:
    container_name: bundlecore-client
    image: bundle-core-frontend
    networks:
      - bundlecore-net
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    networks:
      - bundlecore-net
    # restart: always
    image: bundlecore-django-api
    container_name: bundlecore-backend-django
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - db

volumes:
  data: