# Generated by Django 4.2.9 on 2024-03-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("publication", models.TextField()),
                ("license", models.TextField()),
            ],
            options={
                "db_table": "package_meta",
            },
        ),
        migrations.CreateModel(
            name="PackageVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=255)),
                ("download_url", models.URLField()),
            ],
            options={
                "db_table": "package_version",
            },
        ),
    ]
